name: inses_app
description: Home service booking app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.1
  firebase_analytics: ^8.0.4
  shared_preferences: ^2.0.5
  firebase_remote_config: ^0.10.0
  firebase_crashlytics: ^2.0.4
  flutter_bloc: ^7.0.0
  smooth_page_indicator: ^0.2.3
  equatable: ^2.0.0
  http: ^0.13.3
  line_icons: ^2.0.1
  auto_animated: ^3.0.0
  page_transition: ^2.0.2
  google_sign_in: ^5.0.2
  font_awesome_flutter: ^9.0.0
  dio: ^4.0.0
  path_provider: ^2.0.1
  permission_handler: ^7.1.0
  geolocator: ^7.0.3
  geocoder: ^0.2.1
  image_picker: ^0.8.0+1
  photo_view: ^0.11.1
  share: ^2.0.1
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  razorpay_flutter: ^1.2.6
  webview_flutter: ^2.0.8
  url_launcher: ^6.0.4
  connectivity: ^3.0.6
  http_parser: ^4.0.0
  firebase_messaging: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/images/app.jpg"
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/langs/

  fonts:
    - family: 'logo'
      fonts:
        - asset: font/logo.ttf
    - family: 'font'
      fonts:
        - asset: font/Poppins-Light.ttf
          weight: 100
        - asset: font/Poppins-Regular.ttf
          weight: 200
        - asset: font/Poppins-Medium.ttf
          weight: 300
        - asset: font/Poppins-SemiBold.ttf
          weight: 400
        - asset: font/Poppins-Bold.ttf
          weight: 500
        - asset: font/Poppins-ExtraBold.ttf
          weight: 600
